[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "29oZignwfLQ7J2HszPQ5Jpma3up3xz7SffhNgJCZjEmT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mike/.config/solana/buildspace-solana.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
